server:
  port: 9002
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka
    register-with-eureka: false
    fetch-registry: false

