server:
  port: 9004
spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/talksnap
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka

